### ISSUE TITLE
Failed to compile opengrm. fst/fst.h header not found

### ISSUE THREAD

**Issue by sushanthika23** [alphacep/vosk-api#1033]
checking for fst/fst.h... no configure: error: fst/fst.h header not found make: *** No targets specified and no makefile found. Stop. make: *** No rule to make target 'install'. Stop.

**Comment by nshmyrev** [comment]
We figured out you need to run `./extras/install_opengrm.sh` from `kaldi/tools` folder, not from `kaldi/tools/extras` folder

**Comment by decipher2k** [comment]
@nshmyrev I'm sorry, but that's partially wrong.
OpenFST 1.8.x is not compatible with the buildchain.
Editing the Makefile in kaldi/tools, changing the variable FST_VERSION to 1.6.7, and afterwards running ./extras/install_opengrm.sh from within the kaldi/tools folder will fix the error.

**Comment by nshmyrev** [comment]
@nshmyrev I'm also sorry, I don't understand the context of your comment. What is "buildchain" and so on. We use our own custom version of openfst, I do not recommend 1.6.7.

**Comment by DRMPN** [comment]
> We figured out you need to run `./extras/install_opengrm.sh` from `kaldi/tools` folder, not from `kaldi/tools/extras` folder

Greetings!

I recently encountered the same error while installing on a clean Xubuntu 24.04.2 system. I was already executing the command from the correct folder, but the issue persisted.

@nshmyrev, could you please provide some assistance?

Best regards.

---

**UPD**: Three days later, I managed to resolve the problem. I removed the symlink for OpenFST, ran make, and it worked. Additionally, I downloaded the [alphacep version of OpenFST](https://github.com/alphacep/openfst) and created a symlink pointing to that folder. Although I'm unsure which specific step resolved the issue, the problem was eventually solved.

**Comment by Ragefulll** [comment]
> > We figured out you need to run `./extras/install_opengrm.sh` from `kaldi/tools` folder, not from `kaldi/tools/extras` folder
> 
> Greetings!
> 
> I recently encountered the same error while installing on a clean Xubuntu 24.04.2 system. I was already executing the command from the correct folder, but the issue persisted.
> 
> [@nshmyrev](https://github.com/nshmyrev), could you please provide some assistance?
> 
> Best regards.
> 
> **UPD**: Three days later, I managed to resolve the problem. I removed the symlink for OpenFST, ran make, and it worked. Additionally, I downloaded the [alphacep version of OpenFST](https://github.com/alphacep/openfst) and created a symlink pointing to that folder. Although I'm unsure which specific step resolved the issue, the problem was eventually solved.

Can you please describe step by step how you did it?

**Comment by Haduckientechnology17092005** [comment]
I have failed fst.h error, can you help me fix it clearly?

**Comment by haduckien-raccoon** [comment]
I have failed fst.h error, can you help me fix it clearly?
