### ISSUE TITLE
nodejs binding

### ISSUE THREAD

**Issue by vinnitu** [alphacep/vosk-api#116]
hi!

As I undestand nodejs binding is declared

![image](https://user-images.githubusercontent.com/432168/83328153-960ee800-a289-11ea-9589-dddad1af4ccb.png)

but now implemented yet?

https://github.com/alphacep/vosk-api/blob/master/nodejs/index.js#L2

![image](https://user-images.githubusercontent.com/432168/83328190-dec6a100-a289-11ea-80af-19791cf71b9c.png)

**Comment by nshmyrev** [comment]
You can check https://github.com/antca/vosk-api/tree/nodejs meanwhile

**Comment by nshmyrev** [comment]
I have just pushed a build https://github.com/alphacep/vosk-api/tree/master/nodejs, it should work although I still have to figure out how to build multiarch native binaries properly.

**Comment by vinnitu** [comment]
```The build tested with node-0.10.15, node-0.12 is not yet supported by swig.```

Really 0.10.x? But now 14.x.x actual version.
Why swig instead of n-api?

**Comment by nshmyrev** [comment]
I think 14 should be also supported with some minor tweaks probably. At least deepspeech supports nodejs 14 with swig just fine. Needs testing.

**Comment by Irelynx** [comment]
> I think 14 should be also supported with some minor tweaks probably. At least deepspeech supports nodejs 14 with swig just fine. Needs testing.

Node.JS v12 and v14 by current version of swig is not supported yet (in version 4.0.2, without patches, because of swig usage of v8::Handle, which was deprecated a long time ago. In v12, v14 it was removed from Node.JS, and, maybe, from v8 too (i'm not sure about v8..))

Patches for swig exists now and requires manual build (f.e., see [swig/swig/pull/1746](https://github.com/swig/swig/pull/1746) or ["pr/new-node-fixes"](https://github.com/yegorich/swig/tree/pr/new-node-fixes) branch of [yegorich/swig](https://github.com/yegorich/swig))
The building process of swig itself is easy. if someone want I can describe the build process.

**Comment by nshmyrev** [comment]
I think we will write direct bindings eventually (our interface is pretty simple so it should not be an issue). swig is suboptimal for many use cases as I see now.

**Comment by nshmyrev** [comment]
We have moved to node-ffi-napi bindings, now it should work with napi and it doesn't require kaldi build, you can use prebuilt so file.

https://github.com/alphacep/vosk-api/commit/77b114d434d0721a2cd4791084eaa07f3fd2dd7c

It still needs some love to organize things in classes.

**Comment by nshmyrev** [comment]
More or less working version published:

https://www.npmjs.com/package/vosk/v/0.3.20
