### ISSUE TITLE
Spk Diarization Accuracy

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/vosk-api#175]
After spk vector was fixed in recent push, the spk diarization performance seems get much worse than before.
Sometimes it's even hardly to distinguish a simple conversation between only a man and a woman.

**Comment by dpny518** [comment]
I ran into the same issue, now the cosine similarity is very unreliable. Would it be better to do cosine similarity on the PLDA score rather than the xvector
https://gitee.com/mirrors/kaldi/blob/master/egs/callhome_diarization/v1/diarization/nnet3/xvector/score_plda.sh#L69

or should we normalize the xvectors?
https://gitee.com/mirrors/kaldi/blob/master/egs/callhome_diarization/v1/diarization/calc_cossim_scores.py#L30

**Comment by rafiuddinkhan** [comment]
@qo6xup6 how you are doing the speaker diarization using the speaker recognition module.
https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py
@yondu22 any fixes for the cosine similarity variability.
https://github.com/alphacep/vosk-api/issues/135

**Comment by dpny518** [comment]
@rafiuddinkhan 
You can use this
https://github.com/resemble-ai/Resemblyzer/blob/master/demo02_diarization.py

**Comment by nshmyrev** [comment]
There were bugs unfortunately. Now it is fixed in with new model https://alphacephei.com/vosk/models/vosk-model-spk-0.4.zip and new commit https://github.com/alphacep/vosk-api/commit/41035485dbcabfc9978876c7c36e1c83f64a9c4e

**Comment by nshmyrev** [comment]
Lets track it in #261

**Comment by nshmyrev** [comment]
Or, rather #405
