### ISSUE TITLE
Can't find python.h during building

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/vosk-api#38]
In `python/CMakeLists.txt` Line 6, seems cannot find `python.h`.
```
find_package (Python COMPONENTS Interpreter Development)
```
I'm using anaconda3 for compilation.
I need to hardcode my lib and include path like this:
```
set(Python_INCLUDE_DIR "/opt/anaconda3/envs/python37/include/python3.7m")
set(Python_LIBRARY "/opt/anaconda3/envs/python37/lib/python3.7")
```
Is there a way to fix it?
Cmake version is 3.16.4 btw.

**Comment by nshmyrev** [comment]
If you have custom python installation you can pass it to cmake with Python_ROOT_DIR cmake variable. There is no way to guess that. You can check

https://cmake.org/cmake/help/v3.13/module/FindPython.html

for details

**Comment by qo6xup6** [comment]
Thanks!

**Comment by rohithkodali** [comment]
if using conda environment or python 3.7 and is not specifying any python version (it is taken from the environment) there is a small change to do  in order to use it

PYTHON_INCLUDE_DIR in CmakeLists.txt should be changed to PYTHON_INCLUDE_DIRS. if you are specifying a python version then it is PYTHON_INCLUDE_DIR only.


https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html

for details

**Comment by nshmyrev** [comment]
Fixed now.
