### ISSUE TITLE
The results should be parsed, and here is why

### ISSUE THREAD

**Issue by Sharcoux** [alphacep/vosk-api#462]
The results are currently being returned as JSON string, but they should probably be parsed when requested, or at least, the API should provide a method to retrieved the parsed object. Here is a bunch of reasons why:

1. When documenting the API, a parsed object will be correctly identified by the Intellisense (or any other type detection system), participating to the documentation of the project, avoiding many human errors, and potentially avoiding a loss of time debugging it in the Issues section of this project.
2. If the user is using any type system, they will have to manually declare and cast the type of the results after the parsing, which is kinda boring...
3. When the user parses the JSON, they will have to assume the shape of the object. Any change in the API will remain undetected and the user's application might stop working as expected without any error on his side until runtime.
4. I don't see any way to make any use of the results without parsing them at some point. So why would we let this task to the user?

What I suggest it that we start by providing new methods to retrieve the results, taking care of the parsing, so that we don't break the current API. Then, we can deprecate the old API and remove it in a future version.

**Comment by nshmyrev** [comment]
Thank you @Sharcoux, this is certainly reasonable. We can do that now better than before when we moved from swig which created wrapper automatically. With manual wrapper we are much more flexible.

Another big change I'd like to make is to make system more stream-like, i.e., you just push the audio and get recognition events, possibly many of them. You can push long chunks and short chunks. You get a list of results instead of single result like in google streaming.

Right now we forced to push small chunks and check for AcceptWaveform result again and again which is not really great.  We will rework that part too. Related issue is 

https://github.com/alphacep/vosk-api/issues/31

**Comment by Sharcoux** [comment]
Closed by #467
