### ISSUE TITLE
NodeJS microphone script results completely wrong

### ISSUE THREAD

**Issue by mathewthill** [alphacep/vosk-api#641]
I am using Windows 10 with sox installed correctly

The python microphone script works perfectly but when I try the node js microphone script from the examples folder it results in completely wrong dictation.

Most of the time the partial and text output is "hmm" and random words.

Any ideas why this is happening?

**Comment by sskorol** [comment]
It usually happens if you send data to Vosk in the wrong format (e.g. sample rate). The main diff between NodeJS and Python examples is that in a Python script a sample rate is picked up automatically (unless you manually set it). In NodeJS it's hardcoded to 16k. So it's worth checking your audio device configuration and either adjust it on a system level or just modify a NodeJS script to match your rate. On the other hand, there might be a bunch of other reasons why it's failing. But if it works in Python and doesn't work in NodeJS, it's a 99.9% configuration issue.

**Comment by mathewthill** [comment]
Changing the micInstance section of the demo code completely fixed this issue:

`var micInstance = mic({
    rate: 16000,
    channels: '1',
    debug: false
});`

Using the "rate: String(SAMPLE_RATE)" line prevented the code from working correctly.
