### ISSUE TITLE
[Python] Use of `__del__` for object cleanup

### ISSUE THREAD

**Issue by pradyunsg** [alphacep/vosk-api#670]
Hi there! Thanks for all your work on Vosk!

I noticed that the Python bindings use `__del__` to perform cleanup for the underlying C objects. This is a common antipattern, and is generally a case of misunderstanding what the guarentees Python makes about `__del__` and how they differ from C/C++.

From https://docs.python.org/3/reference/datamodel.html#object.__del__:

> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

This means that it is possible that the various `vosk_*_free` methods that are invoked via `__del__` would not be called by the Python interpreter.

The general pattern to avoid these issues is to either use Cython and it's `__dealloc__`, or to use a [context manager](https://docs.python.org/3/library/stdtypes.html#context-manager-types).

**Comment by nshmyrev** [comment]
Thank you for information. 

Honestly, I don't think that this is a critical issue. It would be a pain to rely on Cython internal things and I'm not sure how context manager applies. The memory will be released on exit anyway and most of the time free method will be properly invoked.

If you have a patch I would consider, otherwise lets keep it as is.

**Comment by nshmyrev** [comment]
Let us know
