### ISSUE TITLE
Some knowledge gaps in the documentation VOSK

### ISSUE THREAD

**Issue by LordKmon** [alphacep/vosk-api#674]
The documentation does not specify the purpose of the "VoskRecognizer.**SetWords**(bool)" method. 
What does it do?

There is also no example of using the SpkModel object. Is there a valid code example out there using SpkModel?

To improve recognition, if I know in advance the potentially spoken words, then how can I apply this in the code?
For example:
```
...
SpkModel spk_model = new SpkModel ("{[Red, Blue, Green]}");
m_VoskRecongize.SetSpkModel (spk_model);
...
```

**Comment by sadrasabouri** [comment]
> The documentation does not specify the purpose of the "VoskRecognizer.**SetWords**(bool)" method.
> What does it do?
> 
There is a JSON field named `result` which is returned after each end of utterance and it's there if and only if you set the `VoskRecognizer.SetWords(True)` and won't be returned otherwise.
It contains some information about the word confidences and start and end of pronunciations of each word, something like this:
```
"result" : [{
      "conf" : 1.000000,
      "end" : 6.840000,
      "start" : 6.150000,
      "word" : "hello"
    }, {
      "conf" : 0.785620,
      "end" : 7.260000,
      "start" : 6.870000,
      "word" : "how"
    }, {
      "conf" : 0.499695,
      "end" : 7.590000,
      "start" : 7.294546,
      "word" : "are"
    }, {
      "conf" : 0.966210,
      "end" : 7.980000,
      "start" : 7.592519,
      "word" : "you"
    }],
```
I really don't know the logic behind this name maybe "Returning a **set** of pronunced **words**" would be a good guess.

> There is also no example of using the SpkModel object. Is there a valid code example out there using SpkModel?
> 

There is actually a example for SpkModel [here](https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py) which you can make use of. 
> To improve recognition, if I know in advance the potentially spoken words, then how can I apply this in the code?
> For example:
> 
> ```
> ...
> SpkModel spk_model = new SpkModel ("{[Red, Blue, Green]}");
> m_VoskRecongize.SetSpkModel (spk_model);
> ...
> ```

Actually it can not be done in this version you should just extract speaker embedding for each utterance - which is by the way something like bellow:
```
[-1.12941, 0.117896, 1.429971, 0.65219, -0.352363, -0.325979, 0.631846, -0.461113, 0.530282, -0.026297, 0.666199, 0.630331, -0.652055, 0.068619, 0.113865, -0.302551, -0.09687, -0.841419, -1.444054, -0.557509, 0.847436, -0.263996, 0.916937, -0.359976, -0.662572, -0.550949, -0.726556, -0.984018, 0.850489, 0.899068, -0.494169, -0.688876, -0.50321, -0.072393, 0.198489, 1.074826, -0.58679, 0.491832, 1.097853, 0.705075, -0.766689, 0.570936, 0.42547, -1.67295, -0.925834, 0.143209, -1.464626, 0.319405, -0.551255, 0.323896, -0.768773, 0.347651, -0.614514, 0.43791, -0.812409, -0.434934, 0.84254, -1.806634, -0.864981, -0.362923, -0.158914, -0.626484, 0.687694, -1.345387, 0.682063, -1.253998, -0.351784, 2.011451, -1.471344, -0.142366, 1.479231, 0.558691, -0.58239, 1.260737, 0.756285, 1.191927, -0.956729, -1.057502, -1.014172, -0.435749, -1.171338, -1.047353, 2.751287, -2.128921, 0.066289, 0.300995, -1.249228, -1.591041, -0.189404, 0.109557, 1.230259, -1.820421, 1.294562, 0.802078, 0.168333, -0.304601, 1.346752, -2.500132, -1.643123, -0.545007, 0.820772, -1.778762, 0.085023, -0.9938, 3.077207, 0.391229, -0.172812, 1.630474, 0.859236, -0.201177, 0.342278, -0.814864, 0.635536, 0.129955, -1.737121, 1.3017, -0.231636, 0.208713, -0.45372, 1.12912, -0.301982, -1.574013, -1.629989, -0.449333, -1.96984, 0.525513, 1.047933, -0.478807]
```
then you can compare your speaker's embedding whit this vector. (by cosine distance metric or other metrics)
Actually there is [PR](https://github.com/alphacep/vosk-api/pull/548) which I'm not sure that vosk-api is going to add it, but it uses a different structure (PLDA scoring instead of Cosine similarity).
