### ISSUE TITLE
nBest List

### ISSUE THREAD

**Issue by qo6xup6** [alphacep/vosk-api#76]
I was wondering is it possible to get nBest list from ASR result instead of only 1?
For example:
['look for movies directed by Terren Tina',
 'look for movies directed by Darren Tina',
 'look for movies directed by Tarantino',
 'look for movies directed by tear and tea no',
 'look for movies directed by Terren teen']

**Comment by YunzhaoLu** [comment]
Does anyone share the idea of returning nbest outputs?

**Comment by sskorol** [comment]
@YunzhaoLu you can check the linked PR to get an idea of how to do it. It might not be the final version though.

**Comment by YunzhaoLu** [comment]
@sskorol Thank you.

**Comment by nshmyrev** [comment]
We have this now with SetMaxAlternatives method.

**Comment by Tetsujinfr** [comment]
Hi,

did anyone play with mixing this SetMaxAlternative feature and a next word model predictor to increase accuracy? If yes, any feedback on the soundness of that approach?

E.g. I was transcribing some audio about space exploration in english (although the speaker has a south african accent, guess who that can be...) with vosk api, which is doing a pretty good work. Simply, from time to time for instance it would detect "launderette" instead of "launchpad", and I was thinking that certainly with some context awareness the transcription should be able to prefer "launchpad" as a higher probability than "launderette".

**Comment by nshmyrev** [comment]
> Simply, from time to time for instance it would detect "launderette" instead of "launchpad"

You can adjust the language model with https://alphacephei.com/vosk/lm

**Comment by Tetsujinfr** [comment]
You mean that the model I am using may not contain "launchpad" in its vocabulary and I should add it? I am using the 1.8GB eng model.

**Comment by nshmyrev** [comment]
The word launchpad is already there, it might just have suboptimal probability.

**Comment by Tetsujinfr** [comment]
Yes so hence why I was looking to use some context awarness model (next word predictor , using BART for example) to pick up lower proba words using a model which tracks the ttranscript domain (space here).
I am not clear what I can do with the language model here though. I understand that the language model tweaking is useful to add vocabulary for abbreviations or proper nouns for example, but in my scenario I am not sure what I can do really. Maybe I am missing something on what LM can bring though.

**Comment by nshmyrev** [comment]
> Maybe I am missing something on what LM can bring though.

Yes. LM is exactly about context awareness.
