### ISSUE TITLE
model without ivector problem

### ISSUE THREAD

**Issue by uouo111845** [alphacep/vosk-api#78]
Hi
I want to know whether this kaldi-android-demo support a model which is not trained with ivector feature. My model works well in this demo, but its size only for the ivector directory is 20M, so I want to test a new model without ivector.

**Comment by daanzu** [comment]
@nshmyrev If you don't mind me asking, what do you mean by "ivector stability problems"?

Possibly relatedly, I tried but then disabled saving of adaptation state between utterances, because accuracy seemed to degrade during prolonged usage sessions. I never did formal testing of whether it ever helped.

**Comment by nshmyrev** [comment]
This has been fixed by afbf330f164745
