### ISSUE TITLE
Android native lib leak

### ISSUE THREAD

**Issue by prechtelm** [alphacep/vosk-api#806]
Hi Team,
we are experiencing a constant increase in memory usage of native code on android until OoM. Even a restart keeps the native objects in memory which results in a crash after 1 - 2 hours which defeats the purpose of continuous voice recognition.
We could trace it down to the native code execution (for example Recognizer.acceptWaveForm() and Recognizer.getResult() which is called in RecognizerThread).
How can we fix this issue?

Used implementations:
implementation group: 'com.alphacephei', name: 'vosk-android', version: '0.3.32'
implementation 'net.java.dev.jna:jna:5.10.0@aar'

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-android-demo/issues/121 ? No need to open multiple issues.

**Comment by prechtelm** [comment]
True, I view this issue as pretty critical. Anything we can do to support you?

**Comment by zhang7249** [comment]
I also encountered memory problems in docker+springboot2+jdk1.8. I did not create model and Recognizer objects during program initialization because they would occupy a lot of memory. This function is not commonly used in my system, so I will create an object every time someone else needs it, but the memory will grow by 600MB after each call. After observation, the memory will not be used for a long time. Actively release it. The program eventually crashed, oom! I am using the latest sdk of java.

    <dependency>
      <groupId>org</groupId>
      <artifactId>jaudiotagger</artifactId>
      <version>2.0.3</version>
    </dependency>

    
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <version>5.14.0</version>
    </dependency>

    <dependency>
      <groupId>com.alphacephei</groupId>
      <artifactId>vosk</artifactId>
      <version>0.3.45</version>
    </dependency>

This is a great sdk, I hope it can be perfect, thank you very much
