### ISSUE TITLE
Model unpack fails without UUID file

### ISSUE THREAD

**Issue by Tadejo9** [alphacep/vosk-api#846]
App fails to unpack the model with the following error:

```
java.lang.Error: Failed to unpack the model: model-en-us/uuid
```
None of the first three english models includes uuid subfolder.

This is the initModel method written using Kotlin. Uuid is not referenced anywhere in my code so i assume it is inside unpack method of StorageService class.

```
private fun initModel() {
        StorageService.unpack(this, "model-en-us", "model",
            { model: Model? ->
                this.model = model!!
                setUiState(AppState.READY)
            }
        ) { exception: IOException ->
            throw Error("Failed to unpack the model: ${exception.message}")
        }
    }
```

I have placed model folder on the same level as src
AndroidStudioProjects/<App-name>/app/src
AndroidStudioProjects/<App-name>/app/model

Is this location false?

**Comment by nshmyrev** [comment]
Hi. UUID file is created by gradle:

https://github.com/alphacep/vosk-android-demo/blob/master/models/build.gradle#L19

**Comment by Tadejo9** [comment]
Hello, thank you for the response.

I figured out that i forgot to add :models to gradle.

**Comment by laurent22** [comment]
@nshmyrev, what is this uuid used for? Is there any way to make it optional? Our problem is that we want to dynamically download the models, then load them in Vosk, but since this uuid is missing, it fails.

We also tried dynamically creating this uuid file where Vosk expects it, but it still fails.

The error is simply:

> Error: /path/to/model/uuid

(and "/path/to/model/uuid" exists and has a random UUID in it)

**Comment by nshmyrev** [comment]
> what is this uuid used for?

To make sure model is sync between storage and aar.

> Is there any way to make it optional? Our problem is that we want to dynamically download the models, then load them in Vosk, but since this uuid is missing, it fails.

If you don't need UUID, simply don't use it. Pick the code from

https://github.com/alphacep/vosk-android-service/tree/master/app/src/main/java/org/vosk/service/download

https://github.com/alphacep/vosk-android-service/blob/master/app/src/main/java/org/vosk/service/VoskRecognitionService.java#L83

**Comment by laurent22** [comment]
Thanks for your answer @nshmyrev. Unfortunately, we lack the knowledge to be able to edit and recompile the Vosk lib, especially since it's imported via another lib (react-native-vosk). What I'm wondering is why when I provide a UUID file, it still gives me this error?

> Error: /path/to/model/uuid

Even though this file exists and has a valid UUID inside. Is there a certain requirement to get this file valid and accepted by the library? For us, that would be the easiest solution to just provide a random uuid, but we can't get that to work unfortunately.

**Comment by laurent22** [comment]
Also why does it need to sync this between the storage and AAR? Our plan is to load the model files directly from storage, not from the AAR. Is it possible with the current implementation of the lib?

**Comment by nshmyrev** [comment]
> Is it possible with the current implementation of the lib?

It is not possible for now

**Comment by nshmyrev** [comment]
@laurent22 sorry, I misunderstood your question, you can obviously download models from the web and put them in storage. See

https://github.com/alphacep/vosk-android-service/tree/master/app/src/main/java/org/vosk/service/download

**Comment by nshmyrev** [comment]
@laurent22 let me know if you want me to implement this part, I can take a look

**Comment by laurent22** [comment]
Thanks @nshmyrev, I have replied on the pull request: https://github.com/laurent22/joplin/pull/8309

**Comment by nshmyrev** [comment]
Good, actually same as https://github.com/alphacep/vosk-android-demo/issues/190
